language: php
sudo: required
php:
  - '5.4'
  - '5.5'
  - '5.6'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE magento;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - wget -O mage-install.sh http://sys.sonassi.com/mage-install.sh
  - chmod +x mage-install.sh
  - bash mage-install.sh -f -r 1.9.1.0 -l 127.0.0.1 -u root -p root -n magento -s -w http://127.0.0.1 -e admin@admin.com

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - mkdir -p build/logs
  - composer require phpunit/phpunit:4.8
  - composer require satooshi/php-coveralls:* --dev

script:
  - composer install --dev --no-interaction
  - vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/behat

after_success:
  - travis_retry php vendor/bin/coveralls
