version: '2'

services:
    php:
        image: pagarme/php:5.4
        volumes:
            - .:/code
        working_dir: /code

    composer:
        image: pagarme/composer
        volumes:
            - .:/code
        working_dir: /code

    selenium:
        image: selenium/hub:2.45.0
        ports:
            - "4444:4444"

    firefox:
        image: selenium/node-firefox-debug:2.45.0
        privileged: true
        depends_on:
            - selenium
        ports:
            - "5900:5900"
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=selenium
            - HUB_PORT_4444_TCP_PORT=4444

    mysql:
        image: mysql:5.6
        env_file: .env

    magento:
        image: ricardotulio/magento:${MAGENTO_VERSION}
        env_file: .env
        volumes:
            - .:/docker-magento-modules/pagarme/
        working_dir: /var/www
        ports:
            - "80:80"
        depends_on:
            - mysql

volumes:
    config:
        driver: local
